### ISSUE TITLE
invalid option: --server

### ISSUE THREAD

**Issue by dogweather** [minitest/minitest-autotest#19]
With Ruby 3.3.0 and Minitest 5.23.1

**Comment by blowmage** [comment]
Hi @dogweather, thank you for opening this issue. I'm sorry you are seeing unexpected behavior. Unfortunately we can't reproduce a "invalid option: --server" message. Can you provide more information about your setup so we can reproduce the behavior you are seeing? What other gems are are installed? Where is this message being displayed?

**Comment by zenspider** [comment]
No response, closing
